services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=${MONGO_URI}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - PORT=${PORT}
      - ENV=${ENV}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - frontend-network

  mongo:
    image: mongo:latest
    command: ["--auth", "--quiet"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet --eval \"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
