version: '3.8'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - frontend-network
      - backend-network

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - frontend-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
