services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/backend:/app
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=dev
      - APP_USER=air
      - MONGO_URI=mongodb://devroot:devpassword@mongo:27017/?authSource=admin

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "5174:5173"

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devroot
      - MONGO_INITDB_ROOT_PASSWORD=devpassword
